# Generated by Django 4.2.23 on 2025-08-11 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(0, 'Cosmic'), (1, 'Ocean'), (2, 'Forest'), (3, 'Sunset')], default=0)),
                ('background_colour', models.CharField(max_length=100)),
                ('note_color', models.CharField(max_length=100)),
                ('font', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('name', models.CharField(default='anonymous', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.IntegerField(choices=[(0, 'Uncategorized'), (1, 'Stress'), (2, 'Depression'), (3, 'Anxiety')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StickerTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='stickers/')),
                ('category', models.IntegerField(choices=[(0, 'Cosmic'), (1, 'Ocean'), (2, 'Forest'), (3, 'Sunset')], default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('rotation', models.FloatField(default=0.0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='quote.note')),
                ('sticker_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stickertypemodel')),
            ],
        ),
    ]
