# Generated by Django 4.2.23 on 2025-08-13 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Uncategorized'), (1, 'Stress'), (2, 'Depression'), (3, 'Anxiety')], default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, default='anonymous', max_length=100),
        ),
    ]
