# Generated by Django 4.2.23 on 2025-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Cosmic'), (1, 'Ocean'), (2, 'Forest'), (3, 'Sunset')], default=0),
        ),
        migrations.AlterField(
            model_name='stickertypemodel',
            name='category',
            field=models.IntegerField(choices=[(0, 'Cosmic'), (1, 'Ocean'), (2, 'Forest'), (3, 'Sunset')], default='0'),
        ),
    ]
