# Generated by Django 4.2.23 on 2025-08-16 20:29

from django.conf import settings
from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0002_alter_note_author_alter_note_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=1, on_delete=models.SET(quote.models.get_removed_user), related_name='notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
        migrations.DeleteModel(
            name='StickerTypeModel',
        ),
    ]
