# Generated by Django 4.2.23 on 2025-08-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_note_author_delete_sticker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='approved',
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
