# Generated by Django 4.2.23 on 2025-08-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_remove_note_approved_note_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
