# Generated by Django 4.2.23 on 2025-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('body', models.TextField()),
                ('contact_reason', models.CharField(max_length=200)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
    ]
